### ISSUE TITLE
Important: store the database in its own volume definition

### ISSUE THREAD

**Issue by Mec-iS** [batcypher/sample-credit#5]
The database persistence layer should be stored in a separated volume

https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes-for-services-swarms-and-stack-files

> In the absence of having named volumes with specified sources, Docker creates an anonymous volume for each task backing a service. Anonymous volumes do not persist after the associated containers are removed.

example:
```
...
  mysql:
    image: mysql
    volumes:
       - db-data:/var/lib/mysql/data
    networks:
       - overlay
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr

volumes:
  db-data:
  ...
```
